name: Swift

on: [pull_request]

jobs:
  danger:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: bundle install
    - name: Run Lint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec fastlane run_lint
